### ISSUE TITLE
Project ID

### ISSUE THREAD

**Issue by krish-shahh** [lowmess/lameass.recipes#165]
How do I access the project ID and how would I get it through Sanity.

**Comment by lowmess** [comment]
You'll need to [create your own Sanity.io project](https://www.sanity.io/docs/getting-started). You can find the project ID in the Sanity.io dashboard. If I have time in the next few days, I'll open source the one we're using here, but in the meantime [here's our schema](https://gist.github.com/lowmess/f06523b572688972ab15bde0b1fcde3e) which should help you get started.
